repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: end-of-file-fixer
      files: .*\.*.py
    - id: trailing-whitespace
      files: .*\.*.py
    - id: debug-statements
    - id: check-ast
    - id: check-added-large-files
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: requirements-txt-fixer
      args:
        - requirements.txt
        - requirements-dev.txt

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.257
  hooks:
    - id: ruff

- repo: https://github.com/tox-dev/pyproject-fmt
  rev: "0.9.2"
  hooks:
    - id: pyproject-fmt